services:
  db:
    image: postgres:17.5
    restart: always
    container_name: guana-vive-postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data